export declare enum SettlementStatus {
  CREATED = 'CREATED',
  IMPORTED = 'IMPORTED',
  VALIDATED = 'VALIDATED',
  IMPORT_APPROVED = 'IMPORT_APPROVED',
  LOCKED = 'LOCKED',
  FUNDS_CLEARED = 'FUNDS_CLEARED',
  PAID = 'PAID',
}
export declare enum DocumentType {
  REMITTANCE = 'REMITTANCE',
  SETTLEMENT_DETAIL = 'SETTLEMENT_DETAIL',
  REVENUE_DISTRIBUTION = 'REVENUE_DISTRIBUTION',
  ADVANCE_ADVICE = 'ADVANCE_ADVICE',
  CREDIT_DEBIT = 'CREDIT_DEBIT',
  POSTING_TICKET = 'POSTING_TICKET',
  UNKNOWN = 'UNKNOWN',
}
export declare enum DriverRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  MATCHED = 'MATCHED',
}
export declare enum AdjustmentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
export declare enum AuditAction {
  BATCH_CREATED = 'BATCH_CREATED',
  IMPORT_UPLOADED = 'IMPORT_UPLOADED',
  IMPORT_APPROVED = 'IMPORT_APPROVED',
  BATCH_LOCKED = 'BATCH_LOCKED',
  FUNDS_CLEARED = 'FUNDS_CLEARED',
  BATCH_PAID = 'BATCH_PAID',
  ADJUSTMENT_CREATED = 'ADJUSTMENT_CREATED',
  ADJUSTMENT_APPROVED = 'ADJUSTMENT_APPROVED',
  ADJUSTMENT_REJECTED = 'ADJUSTMENT_REJECTED',
}
//# sourceMappingURL=enums.d.ts.map
